apiVersion: v1
kind: Namespace
metadata:
  name: yellowjobs-fetcher-prod

---
apiVersion: v1
kind: Service
metadata:
  name: yellowjobs-fetcher-prod
spec:
  type: NodePort
  selector:
    app: yellowjobs-fetcher-prod
  ports:
    # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 4000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yellowjobs-fetcher-prod
spec:
  selector:
    matchLabels:
      app: yellowjobs-fetcher-prod
  replicas: 1
  template:
    metadata:
      labels:
        app: yellowjobs-fetcher-prod
    spec:
      containers:
        - name: yellowjobs-fetcher-prod
          image: docker.io/ans29hul/yellowjobs-fetcher-prod:latest
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: yellowjobs-fetcher-prod-env
                  key: MONGO_URI
            - name: BEARER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: yellowjobs-fetcher-prod-env
                  key: BEARER_TOKEN

          ports:
            - containerPort: 4000
              protocol: "TCP"
